### ISSUE TITLE
Occasionally spots assigned incorrect arrays

### ISSUE THREAD

**Issue by kimspindel** [SpatialTranscriptomicsResearch/st_spot_detector#31]
For example, if the spot at position (25, 1) is located at (25.543, 1.031), then it will actually be assigned to position (26, 1).

This problem also negatively affects the column and row position averages, which are used to find additional "missing" spots.

A better solution needs to be determined, something more dynamic which takes the positions of the surrounding rows and columns into account and the positions of the spots which are already determined.

**Comment by ludvb** [comment]
dffd210 improves row/column position detection. Since 05b86e8, it's possible to reassign spots to new array coordinates in case something goes wrong.
