### ISSUE TITLE
Frame cluster spots should not be returned as spots

### ISSUE THREAD

**Issue by kimspindel** [SpatialTranscriptomicsResearch/st_spot_detector#32]
The spots (2, 2) -> (5, 5) are part of the frame and do not contain spatial transcript information.

**Comment by ludvb** [comment]
I don't think there's any reason to discard these spots from the output; they will be discarded when the spot file is joined with the count data anyway. Maybe they can be interesting for some applications, too, who knows ;). Keeping these spots also improves compatibility with alternative array layouts. Overall, I think it's a good design principle to not impose constraints unless the value add is significant.
