### ISSUE TITLE
Frame/spot adjustment should take mouse centre offset into account

### ISSUE THREAD

**Issue by kimspindel** [SpatialTranscriptomicsResearch/st_spot_detector#36]

**Comment by ludvb** [comment]
Collision detection on foreground annotations (calibrator lines and spots) will be improved in v.1.2.0 (a46beff36bb95f8f4767de2e04d0ad5655f8c0c6, 2fddce688f274a4141e874c8e7ecb324a8c1f540). Closing as of now but feel free to reopen.
