### ISSUE TITLE
Add brightness/contrast/opacity controls to spot adjustment

### ISSUE THREAD

**Issue by kimspindel** [SpatialTranscriptomicsResearch/st_spot_detector#38]
It can be nice to be see both layers at the same time when determining which spots should be added or deleted, as well as increasing brightness and contrast for dull Cy3 images.

**Comment by ludvb** [comment]
Since 3bf19e3, adjustments that are applied in the image adjustment tab are kept when switching to other tabs. I don't think being able to see both images at the same time adds more value than it costs in terms of cluttering the UI. Closing this for the time being but feel free to reopen.
