### ISSUE TITLE
Greyscale Cy3 grid causes error during spot detection

### ISSUE THREAD

**Issue by JoelRV** [SpatialTranscriptomicsResearch/st_spot_detector#54]
For some reason, when using a greyscale image for the Cy3 grid input (as send by your lab after a training course), I systematically obtain this error: 
`An error occured! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html> <head> <title>Error: 500 Internal Server Error</title> <style type="text/css"> html {background-color: #eee; font-family: sans-serif;} body {background-color: #fff; border: 1px solid #ddd; padding: 15px; margin: 15px;} pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;} </style> </head> <body> <h1>Error: 500 Internal Server Error</h1> <p>Sorry, the requested URL <tt>&#039;http://localhost:8080/detect_spots?BR=%7B%22x%22:17602,%22y%22:15836%7D&amp;TL=%7B%22x%22:3493,%22y%22:842%7D&amp;array_size=%7B%22x%22:33,%22y%22:35%7D&amp;brightness=0&amp;contrast=200&amp;session_id=12f8602922c349e14ef173581e414cd5eb7910dc6226f111afdf74e2141d9ec9e6624b9865b3ac40a97b19f8baeda5488869658c042be114f28b5036f67b9e1b&amp;threshold=50&#039;</tt> caused an error:</p> <pre>Internal Server Error</pre> </body> </html> `

I found a workaround by colourizing the white colour space to a yellow scale, which seems to allow for spot detection (without knowing if this has an unwanted effect on the detection algorithm).

Since this is not specified in the official documentation, I wanted to let you guys know.

All the best!

**Comment by ludvb** [comment]
Thanks for reporting this! The spot detector only accepts RGB images at the moment, but it would be quite easy to add support for grayscale images, too (PRs are welcome).

In the meantime, you should be fine converting your grayscale images to RGB. In fact, the server converts the Cy3 image to grayscale before running the spot detector anyway. As a result, your workaround should not have any impact on the detection algorithm.

**Comment by ludvb** [comment]
This has now been fixed in d4b76092c861ed54492dbe572e8b6fec348585a7 and will be merged to master in the coming weeks.
